-- Data Base for MySQL 5.*.* 
-- Made in HeidiSQL Win64
-- Host 127.0.0.1 DataBase: peluqueria

-- Hecha por:
-- Alejandro Perez
-- Santiago Pelaez
-- Raul Capellan

DROP DATABASE IF EXISTS `peluqueria`;

CREATE DATABASE `peluqueria`;

USE peluqueria;

DROP TABLE IF EXISTS `empleados`;

CREATE TABLE `empleados` (
  `DNI` VARCHAR(9) NOT NULL ,
  `NOMBRE` varchar(45) NOT NULL,
  `APELLIDOS` varchar(45) NOT NULL,
  `FECHA_CONTRATACION` date NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `CALLE` varchar(100) NOT NULL,
  `PISO` varchar(100) DEFAULT NULL,
  `CIUDAD` varchar(100) NOT NULL,
  `PROVINCIA` varchar(100) NOT NULL,
  `CODIGO_POSTAL` varchar(5) NOT NULL,
  PRIMARY KEY (`DNI`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;


DROP TABLE IF EXISTS `almacen`;

CREATE TABLE `almacen` (
  `ID_ALMACEN` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NOMBRE_ALMACEN` VARCHAR(100) NOT NULL,
  `CANTIDAD` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID_ALMACEN`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;


DROP TABLE IF EXISTS `productos`;

CREATE TABLE `productos` (
  `ID_PRODUCTO` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NOMBRE_PRODUCTO` varchar(45) NOT NULL,
  `CANTIDAD` BIGINT(20) NOT NULL,
  `ID_ALMACEN` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID_PRODUCTO`),
  KEY `ALMACEN_FK_idx` (`ID_ALMACEN`),
  CONSTRAINT `ALMACEN_FK` FOREIGN KEY (`ID_ALMACEN`) REFERENCES `almacen` (`ID_ALMACEN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;


DROP TABLE IF EXISTS `ventas`;

CREATE TABLE `ventas` (
  `ID_VENTA` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FECHA_VENTA` date NOT NULL,
  `TOTAL_VENTA` BIGINT(20) NOT NULL,
  `DNI` VARCHAR(9) NOT NULL ,
  `ID_PRODUCTO` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID_VENTA`),
  KEY `EMPLEADO_FK_idx` (`DNI`),
  CONSTRAINT `EMPLEADO_FK` FOREIGN KEY (`DNI`) REFERENCES `empleados` (`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  KEY `PRODUCTO_FK_idx` (`ID_PRODUCTO`),
  CONSTRAINT `PRODUCTO_FK` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `productos` (`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;